d __thiscall RBX::Network::Server::ClientProxy::ClientProxy(
        RBX::Network::Server::ClientProxy *this,
        SystemAddress systemAddress,
        RBX::Network::Server *server)
{
  RakPeerInterface *FaceId; // eax

  FaceId = RBX::Feature::getFaceId(server);
  RBX::Network::Replicator::Replicator(this, systemAddress, FaceId);
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::GuidItem<RBX::Instance>::__vftable = (RBX::Network::Server::ClientProxy_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::GuidItem<RBX::Instance>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::AbstractFactoryProduct<RBX::Instance>::RBX::Creatable<RBX::Instance>::RBX::Object::__vftable = (RBX::AbstractFactoryProduct<RBX::Instance>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::AbstractFactoryProduct<RBX::Instance>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Reflection::Described<RBX::Instance,&RBX::sInstance,RBX::Reflection::DescribedBase>::RBX::Reflection::DescribedBase::RBX::Reflection::SignalSource::__vftable = (RBX::Reflection::Described<RBX::Instance,&RBX::sInstance,RBX::Reflection::DescribedBase>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Reflection::Described<RBX::Instance,&char const * const RBX::sInstance,RBX::Reflection::DescribedBase>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Debugable::__vftable = (RBX::Debugable_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Debugable'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Notifier<RBX::Instance,RBX::ChildAdded>::__vftable = (RBX::Notifier<RBX::Instance,RBX::ChildAdded>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Notifier<RBX::Instance,RBX::ChildAdded>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Notifier<RBX::Instance,RBX::ChildRemoved>::__vftable = (RBX::Notifier<RBX::Instance,RBX::ChildRemoved>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Notifier<RBX::Instance,RBX::ChildRemoved>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Notifier<RBX::Instance,RBX::DescendentAdded>::__vftable = (RBX::Notifier<RBX::Instance,RBX::DescendentAdded>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Notifier<RBX::Instance,RBX::DescendentAdded>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Notifier<RBX::Instance,RBX::DescendentRemoving>::__vftable = (RBX::Notifier<RBX::Instance,RBX::DescendentRemoving>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Notifier<RBX::Instance,RBX::DescendentRemoving>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Notifier<RBX::Instance,RBX::AncestorChanged>::__vftable = (RBX::Notifier<RBX::Instance,RBX::AncestorChanged>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Notifier<RBX::Instance,RBX::AncestorChanged>'};
  this->RBX::Network::Replicator::RBX::DescribedNonCreatable<RBX::Network::Replicator,RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Reflection::Described<RBX::Network::Replicator,&RBX::Network::sReplicator,RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator> >::RBX::NonFactoryProduct<RBX::Network::IdSerializer,&RBX::Network::sReplicator>::RBX::Network::IdSerializer::RBX::Instance::RBX::Notifier<RBX::Instance,RBX::PropertyChanged>::__vftable = (RBX::Notifier<RBX::Instance,RBX::PropertyChanged>_vtbl *)&RBX::Network::Server::ClientProxy::`vftable'{for `RBX::Notifier<RBX::Instance,RBX::PropertyChanged>'};
  this->RBX::Network::Replicator::PluginInterface::__vftable = (PluginInterface_vtbl *)&RBX::Network::Server::ClientProxy::`vftable';
  this->remotePlayer.px = 0;
  this->remotePlayer.pn.pi_ = 0;
  this->server = server;
}
